### ISSUE TITLE
Use changelog bullet character that's already in use on other items.

### ISSUE THREAD

**Issue by vaind** [getsentry/github-workflows#15]
Markdown in changelog.md allows users to use either `*` or `-` for an unordered (bullet) list. Currently, the code that updates the changelog always adds new items with `-`. 

Instead, the script should determine what separator is in use and use that instead so that the changelog keeps looking good in its raw source form.

**Comment by marandaneto** [comment]
One of the reasons is that pub.dev has a default pattern for changelog items.
