### ISSUE TITLE
Should we change the bump changelog entries from Features to Bump or Upgrade?

### ISSUE THREAD

**Issue by marandaneto** [getsentry/github-workflows#17]
https://github.com/getsentry/github-workflows/blob/main/scripts/update-changelog.ps1

Often we upgrade the Sentry dependencies and it's added as a `Features` changelog entry but it's not always the case.
What if we have a specific section called `Upgrades` or `Bumps`?

Hybrid SDKs such as Flutter and React Native upgrade the Native SDKs because of bug fixes and do not necessarily need to bump a minor just because the Native SDK bumped a minor.
Also, Even if the Native SDKs have new features, often the Hybrid SDKs don't have those features yet.

This is just a discussion, I'm not sure this is the right thing either.

**Comment by vaind** [comment]
Another section name idea: "Dependencies". 

Either way, we could make this configurable (workflow input) if it makes sense.
