### ISSUE TITLE
Recommended workflow for forked PR

### ISSUE THREAD

**Issue by sl0thentr0py** [getsentry/github-workflows#52]
Danger can't update the status on a forked PR and when it's a required check, we can't merge [the PR](https://github.com/getsentry/sentry-ruby/pull/1932) as a result.

>     "::warning::Running from a forked repo. Danger won't be able to post comments and workflow status on the main repo, printing directly."

What's the recommended way to configure this stuff? Some docs/explanation on what to do would be nice.

**Comment by vaind** [comment]
TLDR; don't make the workflow a required check - it will still run and whoever is merging can check the its green before hitting the merge button. I know it's not great...

There [may be a workaround](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/) but so far it was deemed too much trouble to try and get it working (and it also may need to be done for each repo separately so out of scope here).

See the same discussions in this issue https://github.com/getsentry/sentry-dotnet/issues/1004
