### ISSUE TITLE
Update dev deps without changelog update

### ISSUE THREAD

**Issue by krystofwoldrich** [getsentry/github-workflows#57]
In `sentry-react-native`, we have the wizard in dev dependencies and I would like the updater to update it, but we don't need this info in the changelog as it's only dev dep.

https://github.com/getsentry/sentry-react-native/pull/2989

**Comment by vaind** [comment]
As [you've already found out](https://github.com/getsentry/sentry-react-native/pull/3117), there's the `changelog-entry` setting on the updater.
